# This is a basic workflow to help you get started with Actions

name: Docker Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
          echo "Hello, world!"
          echo ${{ github.workspace }}
          ls -lart /home/runner/work/NewRepo/NewRepo
          sudo docker build -t tom .
          cp TOKEN.txt ~
          cat ~/TOKEN.txt | sudo docker login docker.pkg.github.com -u PhanindraReddyP --password-stdin
          sudo docker tag tom docker.pkg.github.com/wiproorg/newrepo/tom:1.0
          sudo docker tag tom docker.pkg.github.com/wiproorg/newrepo/tom:latest
          sudo docker push docker.pkg.github.com/wiproorg/newrepo/tom:1.0
          sudo docker push docker.pkg.github.com/wiproorg/newrepo/tom:latest
          
          
          
    
    


